-- 1.Command
-- SELECT ROUND(AVG(rental_rate),3) FROM film;
-- 2. Command
-- SELECT COUNT(title) FROM film WHERE title LIKE 'C%';
-- 3. Command
-- SELECT MAX(length) FROM film WHERE rental_rate = 0.99;
-- 4. Command
-- SELECT COUNT(DISTINCT replacement_cost) FROM film WHERE length > 150;